import { useState } from 'react';
import './Skills.css';
import skillImg from '../logo/lap.png';


function Skills() {
    const [active, setActive] = useState('skills');

    const handleToggle = (divName) => {
        setActive(active === divName ? '' : divName);
    };

    return (
        <>
         <div className='heading'>
                    <h1>Skills</h1>
                </div>
            <div className='container'>
               
                <div className='skill-categories'>
                    <h2 onClick={() => handleToggle('skills')}
                        className={active === 'skills' ? 'active' : ''}
                    >
                        Skills
                    </h2>
                    <h2 onClick={() => handleToggle('studies')}
                        className={active === 'studies' ? 'active' : ''}
                    >
                        Education
                    </h2>
                    <h2 onClick={() => handleToggle('soft-skills')}
                        className={active === 'soft-skills' ? 'active' : ''}
                    >
                        Soft Skills
                    </h2>
                </div>

                <div className="skills-content">
                    {active === 'skills' && (
                        <div className="skill-div">
                            <div className='skill-known'>
                                <p><span className='skills-span'>Security Information and Event Management:</span> <br /> SIEM solutions provide real-time analysis of security alerts generated by applications and network hardware, enabling organizations to detect and respond to threats swiftly and effectively.</p>
                                <p><span className='skills-span'>Extended Detection and Response (XDR):</span> <br /> Intermediate knowledge of leveraging XDR tools to enhance threat detection and streamline incident response across multiple security layers.</p>
                                <p><span className='skills-span'>Email Security:</span> <br /> Intermediate experience implementing security measures to protect against phishing attacks and other email-based threats.</p>
                                <p><span className='skills-span'>Threat Intelligence Analysis:</span> <br /> Intermediate ability to analyze threat data to anticipate potential risks and inform security strategies.</p>
                                <p><span className='skills-span'>Incident Response Management:</span> <br /> Intermediate proficiency in coordinating incident response efforts to mitigate the impact of security breaches.</p>
                                <p><span className='skills-span'>Regex Log Parsing:</span> <br /> Intermediate skills in using regex to extract relevant information from logs for analysis and incident response.</p>
                                <p><span className='skills-span'>Vulnerability Assessment:</span> <br /> Intermediate knowledge of conducting assessments to identify security weaknesses and recommend remediation measures.</p>
                                <p><span className='skills-span'>Firewall Configuration and Management:</span> <br /> Intermediate experience in configuring and managing firewalls to protect network perimeters.</p>
                                <p><span className='skills-span'>Penetration Testing Skills:</span> <br /> Intermediate knowledge of performing penetration tests to identify and exploit vulnerabilities in systems.</p>
                                <p><span className='skills-span'>Malware Analysis and Reverse Engineering:</span> <br /> Intermediate skills in analyzing malware samples to understand their behavior and develop mitigation strategies.</p>
                                <div className="Tools">
                                    <h3>Tools Handled</h3>
                                    <p><span class='skills-span'>Splunk</span><br /> Proficient in log analysis, real-time monitoring, and creating dashboards for data visualization.</p>
                                    <p><span class='skills-span'>Arcsight</span><br /> Experienced in managing security events and implementing SIEM for threat detection.</p>
                                    <p><span class='skills-span'>Cortex XDR</span><br /> Skilled in threat detection and response, integrating endpoint and network data for enhanced security.</p>
                                    <p><span class='skills-span'>Immuniweb</span><br /> Knowledgeable in web application security testing and vulnerability assessment.</p>
                                    <p><span class='skills-span'>Cofense</span><br /> Experienced in email security, phishing detection, and response automation.</p>
                                    <p><span class='skills-span'>Qualys</span><br /> Proficient in vulnerability management, compliance monitoring, and web application scanning.</p>
                                    <p><span class='skills-span'>Trend Micro Endpoint Encryption</span><br /> Hands-on experience with endpoint encryption for data protection and compliance.</p>
                                    <p><span class='skills-span'>Nessus</span><br /> Experienced in vulnerability scanning and network security assessments.</p>
                                </div>
                            </div>
                        </div>
                    )}

                    {active === 'studies' && (
                        <div className="skill-div">
                            <p><span className='span-edu'>Sebastian Matriculation Higher Secondary School</span> <br />
                                <span className='span-marks'>SSLC - 86% (2011)</span></p>
                            <p><span className='span-edu'>Sebastian Matriculation Higher Secondary School</span> <br />
                                <span className='span-marks'>HSC - 83% (2013)</span></p>
                            <p><span className='span-edu'>Sri Sai Ram Engineering College</span> <br />
                                <span className='span-marks'>CGPA - 8.31 / 10 (2017)</span></p>
                        </div>
                    )}

                    {active === 'soft-skills' && (
                        <div className="skill-div">
                            <p><span class='skills-span'>Teamwork</span><br />
                                Experience collaborating across cross-functional teams to deliver high-quality solutions, fostering a supportive and inclusive work environment.
                            </p>
                            <p><span class='skills-span'>Technical Proficiency in Cybersecurity</span><br />
                                In-depth knowledge of cybersecurity tools, protocols, and best practices, ensuring robust security measures and proactive threat mitigation.
                            </p>
                            <p><span class='skills-span'>Problem-Solving Ability</span><br />
                                Analytical thinker with strong problem-solving skills, able to troubleshoot and resolve complex technical issues efficiently and effectively.
                            </p>
                            <p><span className='skills-span'>Communication</span><br />
                                Strong verbal and written communication skills, able to articulate ideas clearly and effectively.
                            </p>
                        </div>
                    )}

                    <div className='skills-content-png'> 
                         <img src={skillImg} alt='Skill Img' /> 
                     </div> 
                </div>
            </div>
        </>
    );
}

export default Skills;
